/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author jhony
 */
public class Temas extends javax.swing.JFrame {

    /**
     * Creates new form Temas
     */
    public Temas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnOscuro = new javax.swing.JButton();
        btnDar = new javax.swing.JButton();
        btnClaro = new javax.swing.JButton();
        btnInte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setText("ELIGE EL TEMA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 240, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-hacia-atras.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        btnOscuro.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnOscuro.setText("OSCURO");
        btnOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOscuroActionPerformed(evt);
            }
        });
        jPanel1.add(btnOscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        btnDar.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnDar.setText("DARCULA");
        btnDar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        btnClaro.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnClaro.setText("CLARO");
        btnClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaroActionPerformed(evt);
            }
        });
        jPanel1.add(btnClaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        btnInte.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnInte.setText("INTELLIJ");
        btnInte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteActionPerformed(evt);
            }
        });
        jPanel1.add(btnInte, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaroActionPerformed
        try {
            // Cambiar a modo oscuro
            UIManager.setLookAndFeel(new FlatLightLaf());

            // Actualizar todos los componentes del JFrame
            SwingUtilities.updateComponentTreeUI(Temas.this);
        } catch (Exception ex) {
            System.err.println("No se pudo cambiar a modo oscuro");
        }
    }//GEN-LAST:event_btnClaroActionPerformed

    private void btnOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOscuroActionPerformed
        try {
            // Cambiar a modo oscuro
            UIManager.setLookAndFeel(new FlatDarkLaf());

            // Actualizar todos los componentes del JFrame
            SwingUtilities.updateComponentTreeUI(Temas.this);
        } catch (Exception ex) {
            System.err.println("No se pudo cambiar a modo oscuro");
        }
    }//GEN-LAST:event_btnOscuroActionPerformed

    private void btnInteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteActionPerformed
        try {
            // Cambiar a modo oscuro
            UIManager.setLookAndFeel(new FlatIntelliJLaf());

            // Actualizar todos los componentes del JFrame
            SwingUtilities.updateComponentTreeUI(Temas.this);
        } catch (Exception ex) {
            System.err.println("No se pudo cambiar a modo oscuro");
        }
    }//GEN-LAST:event_btnInteActionPerformed

    private void btnDarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarActionPerformed
       try {
            // Cambiar a modo oscuro
            UIManager.setLookAndFeel(new FlatDarculaLaf());

            // Actualizar todos los componentes del JFrame
            SwingUtilities.updateComponentTreeUI(Temas.this);
        } catch (Exception ex) {
            System.err.println("No se pudo cambiar a modo oscuro");
        }
    }//GEN-LAST:event_btnDarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClaro;
    private javax.swing.JButton btnDar;
    private javax.swing.JButton btnInte;
    private javax.swing.JButton btnOscuro;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
